const DATA = [
  {
    id: 1,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Draft",
    live_from: "Aug 28, 11:15 AM",
    published_date: "Aug 28, 11:00 AM",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 2,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Draft",
    live_from: "Aug 28, 11:15 AM",
    published_date: "",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 3,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Scheduled",
    live_from: "Aug 28, 11:15 AM",
    published_date: "",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 4,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Live",
    live_from: "Aug 28, 11:15 AM",
    published_date: "Aug 28, 11:00 AM",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 5,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Live",
    live_from: "Aug 28, 11:15 AM",
    published_date: "Aug 28, 11:00 AM",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 6,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Past",
    live_from: "Aug 28, 11:15 AM",
    published_date: "Aug 28, 11:00 AM",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 7,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Draft",
    live_from: "Aug 28, 11:15 AM",
    published_date: "",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 8,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Draft",
    live_from: "Aug 28, 11:15 AM",
    published_date: "",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 9,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Draft",
    live_from: "Aug 28, 11:15 AM",
    published_date: "Aug 28, 11:00 AM",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 10,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Draft",
    live_from: "Aug 28, 11:15 AM",
    published_date: "",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 11,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Draft",
    live_from: "Aug 28, 11:15 AM",
    published_date: "Aug 28, 11:00 AM",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 12,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Draft",
    live_from: "Aug 28, 11:15 AM",
    published_date: "Aug 28, 11:00 AM",
    ends: "Jun 7, 2:45 PM",
  },
  {
    id: 13,
    title: "Daily Horoscope",
    last_modified: "Mar 31, 8:56 PM",
    status: "Draft",
    live_from: "Aug 28, 11:15 AM",
    published_date: "Aug 28, 11:00 AM",
    ends: "Jun 7, 2:45 PM",
  },
];

export default DATA;
